name: "🐛 Bug Report"
description: Report an issue or possible bug
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before you start, please make sure that you could reproduce it in incognito.
  - type: input
    id: url
    attributes:
      label: What is the URL where the issue is happening
      placeholder: https://roadmap.sh
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Output from browser console (if any)
      description: Please copy and paste any relevant log output.
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label:  I am willing to submit a pull request for this issue.
          required: false
